---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    component: prisma
data:
  PRISMA_CONFIG: |
    port: 3005
    databases:
      default:
        connector: postgres
        host: localhost
        database: postgres
        user: admin
        ssl: false
        password: admin
        rawAccess: true
        port: '5432'
        migrations: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-backend-simple
  template:
    metadata:
      labels:
        app: cloud-backend-simple
    spec:
      containers:
      - name: cloud-backend-simple
        image: cloud-backend-simple
        ports:
        - containerPort: 3005
        imagePullPolicy: Never
        resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "800m"
              memory: "800Mi"
        env:
          - name: PRISMA_CONFIG
            valueFrom:
              configMapKeyRef:
                name: prisma-configmap
                key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-backend-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-backend-simple
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 31000